### ISSUE TITLE
build: Fix Windows not building during the release process

### ISSUE THREAD

**Issue by shazow** [vipnode/vipnode#82]
Currently breaking due to https://github.com/karalabe/usb/issues/5

**Comment by shazow** [comment]
@gpersoon That's great, thank you! I'll give that a try next time I do a release build.

**Comment by shazow** [comment]
@gpersoon Don't think your workaround applies here, unfortunately. :(

Was hoping the newest xgo would fix it but apparently not, still need to try vendoring.

```
# github.com/karalabe/usb
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:428:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:428:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:429:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:430:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:431:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:432:35: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD_(DWORD,GetNextLink)(THIS_ DWORD dwLink) PURE;
                                   ^
/usr/share/mingw-w64/include/oledlg.h:433:37: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(SetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD dwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:434:37: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(GetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD *lpdwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:435:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(SetLinkSource)(THIS_ DWORD dwLink,LPWSTR lpszDisplayName,ULONG lenFileName,ULONG *pchEaten,WINBOOL fValidateSource) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:436:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(GetLinkSource)(THIS_ DWORD dwLink,LPWSTR *lplpszDisplayName,ULONG *lplenFileName,LPWSTR *lplpszFullLinkType,LPWSTR *lplpszShortLinkType,WINBOOL *lpfSourceAvailable,WINBOOL *lpfIsSelected) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:437:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(OpenLinkSource)(THIS_ DWORD dwLink) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:438:27: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(UpdateLink)(THIS_ DWORD dwLink,WINBOOL fErrorMessage,WINBOOL fReserved) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:439:27: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(CancelLink)(THIS_ DWORD dwLink) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:442:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUILinkContainerW *LPOLEUILINKCONTAINERW;
                                ^
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:447:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkContainerA,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:447:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkContainerA,IUnknown) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:448:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:449:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:450:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:451:35: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD_(DWORD,GetNextLink)(THIS_ DWORD dwLink) PURE;
                                   ^
/usr/share/mingw-w64/include/oledlg.h:452:37: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(SetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD dwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:453:37: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(GetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD *lpdwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:454:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(SetLinkSource)(THIS_ DWORD dwLink,LPSTR lpszDisplayName,ULONG lenFileName,ULONG *pchEaten,WINBOOL fValidateSource) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:455:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(GetLinkSource)(THIS_ DWORD dwLink,LPSTR *lplpszDisplayName,ULONG *lplenFileName,LPSTR *lplpszFullLinkType,LPSTR *lplpszShortLinkType,WINBOOL *lpfSourceAvailable,WINBOOL *lpfIsSelected) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:456:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(OpenLinkSource)(THIS_ DWORD dwLink) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:457:27: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(UpdateLink)(THIS_ DWORD dwLink,WINBOOL fErrorMessage,WINBOOL fReserved) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:458:27: error: expected declaration specifiers or '...' before 'IOleUILinkContainerA'
     STDMETHOD(CancelLink)(THIS_ DWORD dwLink) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:461:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUILinkContainerA *LPOLEUILINKCONTAINERA;
                                ^
/usr/share/mingw-w64/include/oledlg.h:478:5: error: unknown type name 'LPOLEUILINKCONTAINERW'
     LPOLEUILINKCONTAINERW lpOleUILinkContainer;
     ^
/usr/share/mingw-w64/include/oledlg.h:491:5: error: unknown type name 'LPOLEUILINKCONTAINERA'
     LPOLEUILINKCONTAINERA lpOleUILinkContainer;
     ^
/usr/share/mingw-w64/include/oledlg.h:711:5: error: unknown type name 'LPOLEUILINKCONTAINERW'
     LPOLEUILINKCONTAINERW lpOleUILinkContainer;
     ^
/usr/share/mingw-w64/include/oledlg.h:731:5: error: unknown type name 'LPOLEUILINKCONTAINERA'
     LPOLEUILINKCONTAINERA lpOleUILinkContainer;
     ^
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:767:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUIObjInfoW,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:767:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUIObjInfoW,IUnknown) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:768:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:769:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:770:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:771:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(GetObjectInfo)(THIS_ DWORD dwObject,DWORD *lpdwObjSize,LPWSTR *lplpszLabel,LPWSTR *lplpszType,LPWSTR *lplpszShortType,LPWSTR *lplpszLocation) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:772:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(GetConvertInfo)(THIS_ DWORD dwObject,CLSID *lpClassID,WORD *lpwFormat,CLSID *lpConvertDefaultClassID,LPCLSID *lplpClsidExclude,UINT *lpcClsidExclude) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:773:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(ConvertObject)(THIS_ DWORD dwObject,REFCLSID clsidNew) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:774:28: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(GetViewInfo)(THIS_ DWORD dwObject,HGLOBAL *phMetaPict,DWORD *pdvAspect,int *pnCurrentScale) PURE;
                            ^
/usr/share/mingw-w64/include/oledlg.h:775:28: error: expected declaration specifiers or '...' before 'IOleUIObjInfoW'
     STDMETHOD(SetViewInfo)(THIS_ DWORD dwObject,HGLOBAL hMetaPict,DWORD dvAspect,int nCurrentScale,WINBOOL bRelativeToOrig) PURE;
                            ^
/usr/share/mingw-w64/include/oledlg.h:778:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUIObjInfoW *LPOLEUIOBJINFOW;
                          ^
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:783:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUIObjInfoA,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:783:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUIObjInfoA,IUnknown) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:784:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:785:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:786:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:787:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(GetObjectInfo)(THIS_ DWORD dwObject,DWORD *lpdwObjSize,LPSTR *lplpszLabel,LPSTR *lplpszType,LPSTR *lplpszShortType,LPSTR *lplpszLocation) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:788:31: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(GetConvertInfo)(THIS_ DWORD dwObject,CLSID *lpClassID,WORD *lpwFormat,CLSID *lpConvertDefaultClassID,LPCLSID *lplpClsidExclude,UINT *lpcClsidExclude) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:789:30: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(ConvertObject)(THIS_ DWORD dwObject,REFCLSID clsidNew) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:790:28: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(GetViewInfo)(THIS_ DWORD dwObject,HGLOBAL *phMetaPict,DWORD *pdvAspect,int *pnCurrentScale) PURE;
                            ^
/usr/share/mingw-w64/include/oledlg.h:791:28: error: expected declaration specifiers or '...' before 'IOleUIObjInfoA'
     STDMETHOD(SetViewInfo)(THIS_ DWORD dwObject,HGLOBAL hMetaPict,DWORD dvAspect,int nCurrentScale,WINBOOL bRelativeToOrig) PURE;
                            ^
/usr/share/mingw-w64/include/oledlg.h:794:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUIObjInfoA *LPOLEUIOBJINFOA;
                          ^
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:804:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkInfoW,IOleUILinkContainerW) {
   ^
/usr/share/mingw-w64/include/oledlg.h:804:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkInfoW,IOleUILinkContainerW) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:805:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:806:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:807:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:808:35: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD_(DWORD,GetNextLink)(THIS_ DWORD dwLink) PURE;
                                   ^
/usr/share/mingw-w64/include/oledlg.h:809:37: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(SetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD dwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:810:37: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(GetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD *lpdwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:811:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(SetLinkSource)(THIS_ DWORD dwLink,LPWSTR lpszDisplayName,ULONG lenFileName,ULONG *pchEaten,WINBOOL fValidateSource) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:812:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(GetLinkSource)(THIS_ DWORD dwLink,LPWSTR *lplpszDisplayName,ULONG *lplenFileName,LPWSTR *lplpszFullLinkType,LPWSTR *lplpszShortLinkType,WINBOOL *lpfSourceAvailable,WINBOOL *lpfIsSelected) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:813:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(OpenLinkSource)(THIS_ DWORD dwLink) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:814:27: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(UpdateLink)(THIS_ DWORD dwLink,WINBOOL fErrorMessage,WINBOOL fReserved) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:815:27: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(CancelLink)(THIS_ DWORD dwLink) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:816:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoW'
     STDMETHOD(GetLastUpdate)(THIS_ DWORD dwLink,FILETIME *lpLastUpdate) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:819:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUILinkInfoW *LPOLEUILINKINFOW;
                           ^
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:824:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkInfoA,IOleUILinkContainerA) {
   ^
/usr/share/mingw-w64/include/oledlg.h:824:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkInfoA,IOleUILinkContainerA) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:825:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:826:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:827:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:828:35: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD_(DWORD,GetNextLink)(THIS_ DWORD dwLink) PURE;
                                   ^
/usr/share/mingw-w64/include/oledlg.h:829:37: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(SetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD dwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:830:37: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(GetLinkUpdateOptions)(THIS_ DWORD dwLink,DWORD *lpdwUpdateOpt) PURE;
                                     ^
/usr/share/mingw-w64/include/oledlg.h:831:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(SetLinkSource)(THIS_ DWORD dwLink,LPSTR lpszDisplayName,ULONG lenFileName,ULONG *pchEaten,WINBOOL fValidateSource) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:832:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(GetLinkSource)(THIS_ DWORD dwLink,LPSTR *lplpszDisplayName,ULONG *lplenFileName,LPSTR *lplpszFullLinkType,LPSTR *lplpszShortLinkType,WINBOOL *lpfSourceAvailable,WINBOOL *lpfIsSelected) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:833:31: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(OpenLinkSource)(THIS_ DWORD dwLink) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:834:27: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(UpdateLink)(THIS_ DWORD dwLink,WINBOOL fErrorMessage,WINBOOL fReserved) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:835:27: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(CancelLink)(THIS_ DWORD dwLink) PURE;
                           ^
/usr/share/mingw-w64/include/oledlg.h:836:30: error: expected declaration specifiers or '...' before 'IOleUILinkInfoA'
     STDMETHOD(GetLastUpdate)(THIS_ DWORD dwLink,FILETIME *lpLastUpdate) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:839:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
   typedef IOleUILinkInfoA *LPOLEUILINKINFOA;
                           ^
/usr/share/mingw-w64/include/oledlg.h:952:5: error: unknown type name 'LPOLEUIOBJINFOW'
     LPOLEUIOBJINFOW lpObjInfo;
     ^
/usr/share/mingw-w64/include/oledlg.h:954:5: error: unknown type name 'LPOLEUILINKINFOW'
     LPOLEUILINKINFOW lpLinkInfo;
     ^
/usr/share/mingw-w64/include/oledlg.h:965:5: error: unknown type name 'LPOLEUIOBJINFOA'
     LPOLEUIOBJINFOA lpObjInfo;
     ^
/usr/share/mingw-w64/include/oledlg.h:967:5: error: unknown type name 'LPOLEUILINKINFOA'
     LPOLEUILINKINFOA lpLinkInfo;
     ^
/usr/share/mingw-w64/include/oledlg.h:1023:38: error: unknown type name 'LPOLEUILINKCONTAINERW'
   STDAPI_(WINBOOL) OleUIUpdateLinksW(LPOLEUILINKCONTAINERW lpOleUILinkCntr,HWND hwndParent,LPWSTR lpszTitle,int cLinks);
                                      ^
/usr/share/mingw-w64/include/oledlg.h:1024:38: error: unknown type name 'LPOLEUILINKCONTAINERA'
   STDAPI_(WINBOOL) OleUIUpdateLinksA(LPOLEUILINKCONTAINERA lpOleUILinkCntr,HWND hwndParent,LPSTR lpszTitle,int cLinks);
                                      ^
In file included from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/libs.go:56:0:
/go/pkg/mod/github.com/karalabe/usb@v0.0.0-20191104083709-911d15fe12a9/hidapi/windows/hid.c:77:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wstringop-overflow"
```

**Comment by Lebowski1234** [comment]
I'm not sure if this will help, but I just had a similar list of errors when building geth on Windows. The last time I built geth was version 1.8.xx and I had no issues. I decided to upgrade to 1.9.9 today and all of a sudden a whole load of errors associated with mingw64 came up and the build failed. 

I realized that I was using a very old version of mingw64 (version 5.3.0), which worked fine with geth v1.8. I upgraded to version 8.1.0 (in windows: choco upgrade mingw), and this allowed me to successfully build geth versions from 1.9 onwards. 

Again, not sure if this is relevant to your issue, but you could try upgrading mingw.

**Comment by shazow** [comment]
@Lebowski1234 Good thought. Since we're using xgo, updating mingw in the xgo base docker image is probably what we need to do: https://github.com/karalabe/xgo/blob/master/docker/base/Dockerfile

**Comment by charliehorse55** [comment]
@Lebowski1234 +1, worked for me. 

A note - 8.1 is the gcc version, not the mingw version. I believe you upgraded from mingw 5 to mingw 6. 6 is included in ubuntu >= 19.04, or there is a  backport available here: https://launchpad.net/~mati865/+archive/ubuntu/mingw-w64
